eval_only: true
data_path_train: /root/autodl-tmp/hychen/TSSC_stage1_dataset/train
data_path_test: /root/autodl-tmp/hychen/TSSC_stage1_dataset/test
pretrained_vae_model_path: ../ckpts/
results_dir: ../Results/runs_mask_v3
pretrained: /root/autodl-tmp/hychen/TSSC-Net-main_0115/Stage1/Results/runs_mask_v3/MVIF-L-2_step-500_aug_1/checkpoints/epoch_010.pth
resume_from_checkpoint: false
test_ckpt: epoch_020.pth
test_ckpt_mode: ema
gpu_id: '0'
test_gpu_id: '0'
cur_date: step-500_aug_1
model: MVIF-L/2
tar_num_frames: 12
image_size: 256
diffusion_steps: 500
learn_sigma: true
train_batch_size: 1
val_batch_size: 1
test_batch_size: 1
save_ceph: true
learning_rate: 5.0e-05
ckpt_every_iter: 5000
clip_max_norm: 1.0
start_clip_iter: 500
max_train_steps: 80000000
timestep_respacing_train: ''
timestep_respacing_test: ddim50
val_interval: 10
global_seed: 3407
num_workers: 8
log_every: 600
lr_warmup_steps: 0
gradient_accumulation_steps: 32
num_classes: 1
use_compile: false
mixed_precision: true
enable_xformers_memory_efficient_attention: false
gradient_checkpointing: true
